### PR TITLE
Improve non-maintainer signer flow

### LINKED ISSUE #207: Running tool multiple times on the same signing event fails due to existing remote branch
`git push` fails when trying to run the tool a second time for the same signing event where the event branch has changed. The git push is rejected by remote due to the branch name already existing on my forked remote and being a non-fast-forward change.

My local git repository state is the same as immediately following the previous succesful signing event, but the remote barnch (fork) state has changes.

> Press enter to push signature(s) to origin/sign/staging-with-more-signers:
> To https://github.com/joshuagl/root-signing-staging.git
>  ! [rejected]        HEAD -> sign/staging-with-more-signers (non-fast-forward)
> error: failed to push some refs to 'https://github.com/joshuagl/root-signing-staging.git'
> hint: Updates were rejected because a pushed branch tip is behind its remote
> hint: counterpart. Check out this branch and integrate the remote changes
> hint: (e.g. 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> Traceback (most recent call last):
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/bin/tuf-on-ci-sign", line 8, in <module>
>     sys.exit(sign())
>              ^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/tuf_on_ci_sign/sign.py", line 75, in sign
>     git_echo(
>   File "/Users/joshuagl/Projects/github/sigstore/root-signing-staging/.venv/lib/python3.12/site-packages/tuf_on_ci_sign/_common.py", line 97, in git_echo
>     subprocess.run(cmd, check=True, text=True)
>   File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['git', 'push', '--progress', 'origin', 'HEAD:refs/heads/sign/staging-with-more-signers']' returned non-zero exit status 1.

### LINKED ISSUE #208: improve PR experience to signing event
## Problem 

This is about the non-maintainer signing event flow:
* signer runs tuf-on-ci-sign, this pushes a branch to their fork
* now signer needs to create a PR to the signing event

The second step is not obvious and a little annoying: it makes the non-maintainer flow much more work than the maintainer flow.

## Possible solutions

1. we could just avoid the non-maintainer flow
   * make signers contributors in the project
   * make sure their permissions are reasonable
   * have everyone push to same signing event branch

1. We could make the PR requirement clearer in the tool:
   * try to make git less verbose  to remove the 5+ lines of output
   * Print the "Click link to create PR" ourselves

1. Alternatively we could try to make the pull request in the tool
   * I don't really want to use GitHub API for this as that would require a GH token and that sounds painful to manage
   * I wonder if `gh` tool is common? If it is, we could 
      * check that `gh` exists and that `gh auth status` is ok 
      * if it's available, use `gh pr create`
      * otherwise print the "click link to create PR"
 
 CC @joshuagl and @mnm678

### PR DESCRIPTION
**Pull request by jku**
Improve the non-maintainer signer flow 
* Use `push --force`  to avoid issues when contributing to same signing event multiple times
* Directly open a browser in the open-a-pull-request URL after non-maintainer signing

Fredrik tested this in https://github.com/jku/tuf-demo/pull/101

Fixes #207.
Fixes #208.

### CODE REVIEW

**Comment by jku** [comment]
The lint failures fixed in #210

**Comment by jku** [comment]
Filtering the git output is very annoying: 
* the "remote:" messages go to stderr (there is no way to prevent them from going to stderr)
* the moment you redirect STDERR, git decides it's not on a tty
  * this changes e.g. input handling (git no longer asks for input in the terminal)
  * in my case that works fine: now openssh agent shows a notification asking me to touch my yubikey instead of a similar message being printed on terminal
  * I have no idea if this is true in most environments or what would happen if you used git password access

**Comment by jku** [comment]
After some discussion the decision is to 
* leave the remote messages visible
* not use unique branch names: it's important that the remote message is not misleading even if we open the browser
* use --force when pushing to fork (with some safety measures in place)

**Comment by jku** [comment]
CC folks who were present in the discussion in Kubecon that lead to this: @kommendorkapten, @joshuagl, @lukpueh, @mnm678.

**Review by kommendorkapten — APPROVED** [review]
Code looks good, and performed a test earlier with good results.

**Pull request merged**
